application: sadovnychyi
version: polymer
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- deferred: on

handlers:
- url: /static
  static_dir: static
- url: /elements
  static_dir: elements
- url: /components
  static_dir: bower_components

- url: /_ah/admin.*
  script: google.appengine.ext.admin.application
  login: admin

- url: .*
  script: main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

# pagespeed:
#   domains_to_rewrite:
#   - dmit.ro
#   enabled_rewriters:
#   - ImageAddDimensions
#   - MinifyCss
#   - InlineJs
#   - InlineImages
#   - CollapseWhitespace
#   - CombineHeads
#   - ElideAttributes
#   - RemoveComments
#   - RemoveQuotes
#   - DeferJs
